# This is a basic workflow to help you get started with Actions

name: build docker image

# Controls when the workflow will run
on:
  push:
    tags:
      - dev-*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install


      - name: Build                   # React Build
        run: npm run build

      - name: Show host info
        run: |
          uname -a
          cat /etc/os-release

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Choose image tag
        run: |
          echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
            IMAGE_TAG=$GITHUB_REF_NAME
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          else
            IMAGE_TAG=$(git rev-parse --short $GITHUB_SHA)
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          fi
          echo "IMAGE_TAG=$IMAGE_TAG"

      - name: Build container image
        run: |
          IMAGE_NAME=${{secrets.DOCKERHUB_ID}}/ugeo_front:$IMAGE_TAG
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME"
          docker build -t $IMAGE_NAME -f x86.dockerfile .
          echo

      - name: Push container image
        run: |
          docker push $IMAGE_NAME
          echo "Pushed container image: $IMAGE_NAME"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./arm.dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_ID}}/ugeo_front:${IMAGE_TAG}_arm
          platforms: |
            linux/arm64